// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamibj5U1X0EsePsKwNRS_3oYceEPiibk',
    appId: '1:946275082988:web:f0878da0d97cf266043bc9',
    messagingSenderId: '946275082988',
    projectId: 'bronco-safe',
    authDomain: 'bronco-safe.firebaseapp.com',
    databaseURL: 'https://bronco-safe-default-rtdb.firebaseio.com',
    storageBucket: 'bronco-safe.appspot.com',
    measurementId: 'G-HR0MPBYWPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK8TZ_E9IBOi_Dct6LGMnM1E2y6FzBeeM',
    appId: '1:946275082988:android:75883c653c5a4f99043bc9',
    messagingSenderId: '946275082988',
    projectId: 'bronco-safe',
    databaseURL: 'https://bronco-safe-default-rtdb.firebaseio.com',
    storageBucket: 'bronco-safe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbY_L4YDarGANSWzVABmPwbNu9SsyHpd4',
    appId: '1:946275082988:ios:c2db738d8bdc79ac043bc9',
    messagingSenderId: '946275082988',
    projectId: 'bronco-safe',
    databaseURL: 'https://bronco-safe-default-rtdb.firebaseio.com',
    storageBucket: 'bronco-safe.appspot.com',
    iosClientId: '946275082988-muv971b7q3s393bk5plbffk449oir7oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.broncoSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbY_L4YDarGANSWzVABmPwbNu9SsyHpd4',
    appId: '1:946275082988:ios:c2db738d8bdc79ac043bc9',
    messagingSenderId: '946275082988',
    projectId: 'bronco-safe',
    databaseURL: 'https://bronco-safe-default-rtdb.firebaseio.com',
    storageBucket: 'bronco-safe.appspot.com',
    iosClientId: '946275082988-muv971b7q3s393bk5plbffk449oir7oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.broncoSafe',
  );
}
